language: node_js

node_js:
  - "lts/*"

before_script:
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$HOME/.meteor:$PATH
  - export REPO=ohif/viewer
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

cache:
  directories:
    - ~/.meteor
    - node_modules
    - OHIFViewer/node_modules

env:
    - METEOR_PACKAGE_DIRS=../Packages
    - COMMIT=${TRAVIS_COMMIT::8}

jobs:
  include:
    - stage: build docker image
      script:
        - echo $COMMIT_HASH
        - docker build -t $REPO:$COMMIT .
        - docker tag $REPO:$COMMIT $REPO:$TAG
        - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
        - docker images