language: node_js

node_js:
  - "lts/*"

before_script:
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$HOME/.meteor:$PATH
  - npm install -g spacejam
  - export COMMIT_HASH=$$(git log -1 --pretty=%!H(MISSING))

cache:
  directories:
    - ~/.meteor
    - OHIFViewer/node_modules

env:
    - METEOR_PACKAGE_DIRS=../Packages

jobs:
  include:
    - stage: build docker image
      script:
        - echo $COMMIT_HASH
        - docker build -t ohif/viewer:${COMMIT_HASH} .
        - docker images